### ISSUE TITLE
Link to User Guide is broken

### ISSUE THREAD

**Issue by joshtynjala** [cedx/setup-hashlink#8]
Looks like the link to the User Guide is currently broken.

https://docs.belin.io/setup-hashlink/

I couldn't find an example documented anywhere. The README would be a good place for a simple one. I ended up figuring it out on my own by digging into .github/workflows/main.yaml, but not everyone will know/guess to look there.

**Comment by cedx** [comment]
Yeah! I've started to port it to Docsify... and, well, it's hard to find time for side projects 😄 
In the meantime, you can look at the wiki: https://github.com/cedx/setup-hashlink/wiki
A sample workflow is also available here: https://github.com/cedx/setup-hashlink/blob/main/example/workflow.yaml

**Comment by joshtynjala** [comment]
I missed the wiki. Thanks!

**Comment by cedx** [comment]
The wiki has finally been migrated to Docsify!
